import { readFileSync, writeFileSync } from "fs";

const data = JSON.parse(readFileSync("courses/drone_training.json", "utf-8"));

data.tracks[0].lessons[1].learning_script = [
  {
    page: 1,
    title: "Introduction: Why Parameter-Efficient Fine-Tuning Changes Everything for Drone AI",
    content: `Foundation models represent some of the most powerful artificial intelligence systems ever created, but they come with a fundamental practical challenge: their sheer size makes them extraordinarily expensive to customize. A state-of-the-art vision-language model might contain billions of parameters, requiring hundreds of gigabytes of GPU memory just to load, let alone train. For drone engineering teams that need to adapt these models to specialized domains like thermal imaging, synthetic aperture radar interpretation, or agricultural health monitoring, the traditional approach of full fine-tuning is simply not feasible.

Parameter-Efficient Fine-Tuning, commonly abbreviated as PEFT, emerged as the practical solution to this problem. The core principle is elegant: instead of retraining all parameters of a large pre-trained model, freeze the vast majority of the network and introduce a small number of new, trainable parameters at strategic locations. These small parameter injections learn to steer the frozen model's behavior toward the desired task while preserving the general knowledge already encoded in the original weights.

For drone AI engineers, PEFT is not merely a convenience — it is an operational necessity. Consider the deployment pipeline for a drone fleet operating across different mission profiles. One week the drones might be conducting wildfire perimeter mapping, the next they might be inspecting solar panel installations. Each mission requires the perception system to recognize different visual patterns and respond to different operational commands. Full fine-tuning for each mission would require expensive GPU clusters and days of training time. With PEFT, the same base model can be rapidly adapted using consumer-grade hardware, and multiple lightweight adapters can be swapped in and out depending on the mission profile.

The most widely adopted PEFT technique is Low-Rank Adaptation, or LoRA. LoRA is based on the mathematical insight that the weight updates during fine-tuning tend to have low intrinsic rank, meaning they can be well-approximated by the product of two much smaller matrices. Instead of updating a weight matrix with dimensions d-by-k (potentially millions of parameters), LoRA learns two matrices of dimensions d-by-r and r-by-k, where r (the rank) is typically 4, 8, or 16. This reduces the number of trainable parameters by orders of magnitude.

QLoRA pushes this efficiency further by combining LoRA with aggressive quantization of the base model. By compressing the frozen model weights from 32-bit floating point to 4-bit NormalFloat representation, QLoRA reduces the memory footprint of the base model by approximately eight times. This means a model that would normally require 80 GB of VRAM can be loaded and fine-tuned on a single GPU with 10 GB of memory. For drone teams working with hardware like the NVIDIA Jetson platform, this compression is the difference between feasibility and impossibility.

This lesson will guide you through the mathematical foundations of LoRA, the practical implementation of QLoRA, the process of preparing drone-specific training data, and the considerations for deploying PEFT-adapted models on edge hardware. Each concept builds toward the practical goal of being able to rapidly customize large foundation models for any drone mission profile.`,
    key_takeaways: [
      "PEFT freezes most model parameters and injects small trainable modules, reducing training cost by orders of magnitude while preserving pre-trained knowledge",
      "LoRA exploits the low-rank structure of fine-tuning weight updates to replace full weight matrices with products of much smaller matrices",
      "QLoRA combines LoRA with 4-bit quantization to enable fine-tuning of billion-parameter models on consumer-grade GPU hardware"
    ]
  },
  {
    page: 2,
    title: "Core Concept: Low-Rank Adaptation (LoRA) Mathematics and Mechanics",
    content: `To truly understand LoRA, we need to appreciate the mathematical insight that makes it work. During standard fine-tuning, the model updates every weight matrix W in the network. For a transformer attention layer with an embedding dimension of 4096, the query projection matrix alone has 4096 times 4096 equals approximately 16.7 million parameters. A model with 24 such layers has over 400 million parameters just in the query projections.

LoRA is built on the observation that the change in weights during fine-tuning, which we call delta-W, tends to occupy a much lower-dimensional subspace than the full weight matrix. In linear algebra terms, the rank of delta-W is typically much smaller than the full rank of the weight matrix. This means delta-W can be approximated as the product of two smaller matrices: a down-projection matrix A of shape d-by-r and an up-projection matrix B of shape r-by-k, where r (the rank) is much smaller than both d and k.

During the forward pass, the output of a LoRA-adapted linear layer becomes: output equals W times x plus (B times A) times x, scaled by alpha divided by r. The original weight matrix W is frozen (no gradients are computed for it), and only the matrices A and B receive gradient updates during training. The scaling factor alpha divided by r controls the magnitude of the LoRA adaptation relative to the original weights. The alpha hyperparameter acts as a learning rate modifier for the LoRA layers: higher alpha values produce larger adaptations.

The initialization strategy is critical. Matrix A is initialized with small random values (typically from a Gaussian distribution), while matrix B is initialized to zero. This means that at the start of training, the LoRA contribution (B times A) is exactly zero, and the model behaves identically to the pre-trained base model. Training then gradually learns the appropriate low-rank update. This zero-initialization is not arbitrary; it ensures that the fine-tuning process starts from the pre-trained solution rather than a random perturbation, which could destabilize training.

The rank parameter r is the most important hyperparameter in LoRA. A rank of 1 means the adaptation is constrained to a one-dimensional subspace — highly restrictive but extremely parameter-efficient. A rank of 64 provides a much richer adaptation space but uses proportionally more parameters. In practice, ranks between 4 and 16 work well for most fine-tuning scenarios. The optimal rank depends on the complexity of the domain shift: adapting a general vision model to a closely related domain might require rank 4, while adapting it to a fundamentally different modality like thermal imaging might benefit from rank 16 or higher.

The choice of target modules — meaning which layers in the model receive LoRA adapters — significantly affects both performance and parameter count. The most common targets are the attention query (q_proj) and value (v_proj) projections, as these layers control what the model attends to and how it aggregates information. Adding LoRA to the key projection (k_proj) and output projection (o_proj) provides additional adaptation capacity. Some practitioners also apply LoRA to the feed-forward network layers (up_proj, down_proj), though this is less common because these layers are already computationally redundant for many fine-tuning tasks.

The dropout parameter (lora_dropout) applies standard dropout regularization to the LoRA layers during training. This is particularly important when fine-tuning on small domain-specific datasets, as is common in drone applications where labeled training data is expensive to collect. A dropout rate of 0.05 to 0.1 is typical, preventing the small LoRA matrices from overfitting to the limited training examples while still allowing them to learn meaningful adaptations.

When the fine-tuning is complete, the LoRA adapter weights are saved in a separate file (adapter_model.bin), which is typically only a few megabytes compared to the multi-gigabyte base model. This separation is operationally powerful: a single base model can be deployed on the drone hardware, and different LoRA adapter files can be loaded or swapped depending on the mission, without duplicating the base model storage.`,
    key_takeaways: [
      "LoRA decomposes weight updates into two small matrices (A and B) whose product approximates the full fine-tuning update in a low-rank subspace",
      "The rank parameter r controls the trade-off between adaptation capacity and parameter efficiency, with ranks 4-16 working well for most drone applications",
      "Zero initialization of matrix B ensures training starts from the pre-trained solution, maintaining stability during fine-tuning",
      "Target modules (typically q_proj and v_proj in attention layers) determine which parts of the model are adapted and directly affect the quality of fine-tuning"
    ]
  },
  {
    page: 3,
    title: "QLoRA: Quantization Meets Low-Rank Adaptation",
    content: `QLoRA represents a breakthrough in making fine-tuning accessible on resource-constrained hardware by combining two complementary techniques: aggressive quantization of the base model and LoRA adapters for the trainable parameters. Understanding QLoRA is essential for drone AI engineers because it directly enables fine-tuning of large vision-language models on hardware that would otherwise be completely insufficient.

Quantization is the process of reducing the numerical precision of model weights from higher bit-widths (like 32-bit floating point) to lower ones (like 8-bit integers or 4-bit representations). The fundamental trade-off is between memory savings and information loss. A 32-bit float can represent approximately 4.3 billion distinct values, while a 4-bit representation can only distinguish 16 values. The challenge is mapping the continuous range of weight values to these 16 discrete levels with minimal loss of model capability.

QLoRA uses a specific 4-bit quantization scheme called NormalFloat4 (NF4), which was designed specifically for neural network weights. NF4 is based on the observation that trained neural network weights approximately follow a normal (Gaussian) distribution. Instead of dividing the value range into 16 equally spaced levels (as standard uniform quantization would), NF4 places its 16 quantization levels at positions that equally divide the cumulative distribution function of a standard normal distribution. This means more quantization levels are concentrated near zero (where most weights cluster) and fewer are allocated to the tails. The result is significantly lower quantization error compared to uniform quantization schemes.

The bitsandbytes library implements this NF4 quantization and integrates directly with the Hugging Face ecosystem. When configuring quantization, the BitsAndBytesConfig specifies the quantization type (nf4 or fp4), whether to use double quantization (which quantizes the quantization constants themselves for additional memory savings), and the compute data type (typically bfloat16 or float16) for the LoRA computations and intermediate activations.

The memory arithmetic is straightforward and dramatic. A 7-billion parameter model stored in 32-bit float requires approximately 28 GB of memory (7 billion times 4 bytes). At 4-bit precision, the same model requires approximately 3.5 GB (7 billion times 0.5 bytes). Adding a LoRA adapter with rank 8 targeting the attention projections adds only a few million parameters at 16-bit precision, perhaps 50-100 MB. The total memory requirement drops from 28 GB (for full fine-tuning at 32-bit with optimizer states and gradients) to under 6 GB (for QLoRA), representing an approximately eight-fold reduction in the memory required to hold the model weights.

The device_map parameter, set to "auto" when loading a quantized model, tells the Hugging Face library to automatically distribute model layers across available devices. On a system with a single GPU, this means loading as much as possible onto the GPU and spilling the remainder to CPU memory. On multi-GPU systems, layers are distributed across GPUs. This automatic placement is essential because quantized models cannot be easily moved between devices after loading; the quantization format is device-specific.

During the forward pass in QLoRA, the quantized base model weights are dequantized on-the-fly to the compute precision (e.g., bfloat16) for the matrix multiplication, then the LoRA contribution is added at the higher precision. This means the forward pass operates at effectively full precision for the computation, while the storage benefits from 4-bit compression. The gradient computation flows only through the LoRA parameters, so the quantized base model weights never receive gradients and remain frozen in their compressed form.

For drone deployment specifically, QLoRA enables a powerful workflow. The base model can be fine-tuned on a workstation with a modest GPU. The resulting LoRA adapter weights are tiny files that can be transferred to the drone over limited-bandwidth communication links. The drone carries the quantized base model in its edge device storage, and different LoRA adapters can be loaded dynamically to switch between mission profiles. This architecture means a drone fleet can be remotely reconfigured for new tasks without physically accessing each unit or transmitting the entire model over the air.`,
    key_takeaways: [
      "NormalFloat4 quantization places quantization levels according to the normal distribution of neural network weights, minimizing information loss compared to uniform quantization",
      "QLoRA reduces memory requirements by approximately 8x compared to full 32-bit fine-tuning while maintaining near-full-precision computation during the forward pass",
      "The combination of quantized base model storage with lightweight LoRA adapters enables remote mission profile switching on drone fleets through small file transfers"
    ]
  },
  {
    page: 4,
    title: "Practical Implementation: Building the Fine-Tuning Pipeline",
    content: `Translating the theory of PEFT into a working fine-tuning pipeline involves several concrete implementation steps, each with decisions that affect the quality of the final model. This section walks through the critical stages of building a LoRA fine-tuning pipeline for drone command models.

The implementation begins with environment setup, and version pinning is essential. The Hugging Face ecosystem (transformers, peft, datasets, bitsandbytes) evolves rapidly, and version mismatches between these libraries are the most common source of cryptic errors. The PEFT library version must be compatible with both the transformers version and the model architecture being adapted. Using a virtual environment with exact version specifications prevents upstream API changes from disrupting the development pipeline.

Model loading with quantization is the next critical step. The BitsAndBytesConfig object specifies the quantization parameters before the model is loaded. Setting load_in_4bit to true activates 4-bit quantization, bnb_4bit_quant_type to "nf4" selects the NormalFloat4 scheme, and bnb_4bit_compute_dtype to bfloat16 sets the precision for compute operations. The model is then loaded with this configuration, and the quantization is applied during the loading process itself. Once loaded, the model weights cannot be unquantized without reloading.

Applying LoRA requires creating a LoraConfig object that specifies the rank (r), the scaling factor (lora_alpha), the dropout rate (lora_dropout), and the target modules. The get_peft_model function then takes the loaded base model and the LoRA configuration, freezes all base model parameters, and injects the LoRA adapter matrices at the specified target layers. After this function call, only the LoRA parameters are trainable. The print_trainable_parameters method provides a useful sanity check, showing the exact number of trainable parameters out of the total model size, which should be well under one percent for a typical LoRA configuration.

Dataset preparation for drone command fine-tuning deserves careful attention. The training data consists of prompt-response pairs where the prompts describe drone operational scenarios and the responses contain the appropriate commands or analysis. For example, a prompt might describe a thermal anomaly detected at specific coordinates, and the response would contain the appropriate flight adjustment commands and investigation protocol. The dataset must be tokenized consistently with the model's expected input format, including proper handling of special tokens, padding, and truncation.

The data collator is responsible for batching the tokenized examples and ensuring consistent sequence lengths within each batch. For causal language models (which generate text left-to-right), the collator must also set up the labels correctly: the labels are typically a shifted copy of the input tokens, where the model learns to predict each token from the preceding context. Tokens corresponding to the prompt portion are often masked (set to -100) in the labels so the loss is computed only on the response portion, teaching the model to generate appropriate responses given the prompt context.

Training arguments control the optimization process. Key parameters include the number of training epochs (typically 3-10 for LoRA fine-tuning), the learning rate (usually higher than full fine-tuning, around 2e-4 to 3e-4, because only the small LoRA matrices are being updated), the batch size per device (constrained by GPU memory), and the gradient accumulation steps. Gradient accumulation is particularly useful for QLoRA training on memory-limited devices: instead of processing a large batch in one forward pass, the system accumulates gradients over multiple smaller batches and performs a single weight update. With a per-device batch size of 1 and gradient accumulation steps of 16, the effective batch size becomes 16 without requiring the memory for 16 simultaneous samples.

After training, the LoRA adapter is saved separately from the base model. The adapter file contains only the A and B matrices for each adapted layer, along with the LoRA configuration. This file is typically just a few megabytes. To use the fine-tuned model for inference, the base model is loaded (optionally quantized), and the LoRA adapter is merged on top. The merge operation adds the product of B and A (scaled by alpha over r) to each adapted weight matrix, producing a single unified model that behaves as if it had been fully fine-tuned. This merged model can then be exported to ONNX and compiled to TensorRT for optimized edge deployment.`,
    key_takeaways: [
      "get_peft_model freezes the base model and injects trainable LoRA matrices at specified target layers, typically reducing trainable parameters to under 1% of total",
      "Gradient accumulation simulates larger batch sizes on memory-constrained hardware by accumulating gradients over multiple forward passes before each weight update",
      "LoRA adapters are saved as small separate files that can be merged with the base model for deployment or kept separate for flexible mission profile switching"
    ]
  },
  {
    page: 5,
    title: "Practical Application: PEFT for Drone Mission Profiles",
    content: `The real power of PEFT becomes apparent when we consider how it transforms the operational model for drone fleet management. Traditional approaches to customizing AI models for specific tasks required significant infrastructure, lengthy training pipelines, and substantial computational budgets. PEFT flattens this complexity, enabling rapid adaptation cycles that match the operational tempo of real-world drone deployments.

Consider a drone fleet deployed for infrastructure inspection across different asset types: bridges, power lines, wind turbines, and solar farms. Each asset type has distinct visual characteristics, failure modes, and inspection protocols. A bridge inspector looks for spalling concrete, rebar exposure, and joint displacement. A power line inspector looks for vegetation encroachment, conductor sag, and insulator damage. A wind turbine inspector focuses on blade erosion, lightning damage, and leading-edge deterioration.

With PEFT, the deployment architecture looks like this: a single large vision-language model serves as the base, deployed on each drone in its quantized form. For each asset type, a LoRA adapter of a few megabytes has been fine-tuned on domain-specific data. Before a mission, the ground station pushes the appropriate adapter file to each drone in the fleet. The drone loads the base model once at startup and swaps the LoRA adapter based on the mission profile. This swap takes milliseconds because only the small adapter matrices need to be loaded into memory.

The data preparation workflow for creating these mission-specific adapters requires careful structuring. Training examples should pair aerial images with text descriptions that use the specific vocabulary and assessment criteria of each inspection domain. For bridge inspection, the text might describe spalling severity grades, crack width measurements, and structural significance assessments. For power line inspection, the descriptions would use utility-specific terminology for component identification and defect classification.

Input validation is especially critical in drone PEFT pipelines. Sensor data from drone cameras can arrive in unexpected formats: dropped frames produce null values, rapid pitch changes create motion blur, and altitude variations change the effective resolution of objects. The fine-tuning pipeline must include robust preprocessing that validates image dimensions, checks for null or corrupted frames, and normalizes the input to the model's expected format before any tensor operations. These defensive programming practices, while seeming overly cautious during development, prevent catastrophic failures during autonomous flight operations.

Asynchronous execution patterns matter when integrating PEFT models into real-time drone control loops. The model inference should run on its own execution thread, decoupled from the main flight control loop. The flight controller operates on strict timing deadlines, typically at 100 Hz or higher. An inference call that blocks the main loop, even briefly, can cause the drone to miss a control cycle, potentially leading to instability. The PEFT model inference runs asynchronously, pushing results to a shared queue that the mission planning module reads at its own pace.

Observability in the deployed system means logging every inference result with its associated metadata: timestamp, GPS position, altitude, camera angle, confidence scores, and the active LoRA adapter identifier. These structured logs serve dual purposes. During the mission, they enable real-time monitoring of the AI system's performance. After the mission, they provide the training data for the next iteration of adapter fine-tuning, creating a continuous improvement loop where each deployment generates data that improves the next generation of adapters.

The adapter iteration cycle enabled by PEFT is remarkably fast compared to traditional model retraining. After a mission, field engineers review the inference results, correct any misclassifications, and add the validated examples to the training dataset. A new LoRA adapter can be trained in minutes to hours (depending on dataset size and hardware), validated against a held-out test set, and deployed to the fleet for the next mission. This rapid iteration cycle means the drone fleet's AI capabilities can improve on a weekly or even daily cadence, adapting to new environments, new asset types, and lessons learned from operational experience.`,
    key_takeaways: [
      "PEFT enables a fleet architecture where one quantized base model serves all missions and lightweight LoRA adapters are swapped per mission profile in milliseconds",
      "Robust input validation and asynchronous execution patterns are essential when integrating PEFT models into real-time drone control loops with strict timing requirements",
      "The rapid adapter iteration cycle means drone AI capabilities can improve on a daily or weekly cadence based on operational feedback"
    ]
  },
  {
    page: 6,
    title: "Common Pitfalls and Debugging Strategies for PEFT",
    content: `Working with PEFT, LoRA, and QLoRA introduces a specific set of failure modes that can be subtle and difficult to diagnose. Understanding these common pitfalls will save significant debugging time.

The most frequent beginner mistake is selecting inappropriate target modules. Applying LoRA only to the query projection (q_proj) while neglecting the value projection (v_proj) severely limits the model's ability to adapt how it aggregates information from attended tokens. The attention mechanism has two distinct phases: computing attention weights (influenced by query and key projections) and computing attention output (influenced by value and output projections). Adapting only one phase leads to imbalanced fine-tuning where the model can change what it attends to but not how it processes what it finds, or vice versa. Always start with at least q_proj and v_proj as target modules.

Rank selection errors manifest in two ways. Setting the rank too low (1 or 2) for a complex domain shift results in underfitting: the adapter does not have enough capacity to learn the necessary adaptations, and the model exhibits poor performance on the target task despite adequate training data. Setting the rank too high (64 or above) wastes parameters and can lead to overfitting on small datasets, where the model memorizes the training examples rather than learning generalizable patterns. The symptoms of overfitting include excellent performance on training data with poor performance on validation data, especially when the validation examples come from slightly different conditions than the training set.

Version incompatibilities between the transformers, peft, and bitsandbytes libraries are an extremely common source of frustration. These libraries are updated frequently, and a method that works with one version combination may produce errors with another. The most defensive approach is to pin exact versions in your requirements file and only update them deliberately, testing the full pipeline after each upgrade. Error messages from version incompatibilities are often misleading, pointing to internal library code rather than the actual version mismatch.

Memory management issues during QLoRA training frequently confuse practitioners. Even though the base model is quantized to 4-bit, the optimizer states for the LoRA parameters are maintained at full precision. The Adam optimizer, which is standard for transformer training, maintains two additional state variables (first and second moment estimates) for each trainable parameter. For a LoRA configuration with, say, 5 million trainable parameters at 16-bit precision, the optimizer states add approximately 40 MB. While this seems small, accumulating gradients, maintaining the computation graph for backpropagation, and storing intermediate activations all contribute to memory pressure. If training crashes with out-of-memory errors despite the model fitting during inference, the solution is usually to reduce the sequence length, reduce the batch size, or enable gradient checkpointing (which trades compute time for memory by recomputing activations during the backward pass instead of storing them).

Incorrect label masking is a subtle bug that dramatically affects fine-tuning quality without producing any obvious errors. In causal language model fine-tuning, the labels for the prompt tokens should be set to -100 (the ignore index for cross-entropy loss). If the prompt tokens are included in the loss computation, the model is being trained to reproduce the prompt text as well as generate the response, which dilutes the training signal and can cause the model to repeat prompt text during inference rather than generating novel responses.

Failing to disable gradient computation during inference after deployment is a LoRA-specific variant of the general transformer pitfall. When a LoRA adapter is merged with the base model for deployment, the resulting model should be used with torch.no_grad() just like any other model. However, some deployment scripts forget this step, especially when the same code path is used for both training and inference. The memory overhead of tracking gradients during inference can push an otherwise feasible edge deployment over the memory limit.

Another common error is applying the wrong adapter to the wrong base model version. If the base model is updated or replaced, previously trained LoRA adapters become incompatible because the layer dimensions and internal representations have changed. Even minor version updates to a model (e.g., from version 1.0 to 1.1) can invalidate existing adapters. Always store the base model identifier alongside the adapter weights and validate compatibility at loading time.`,
    key_takeaways: [
      "Always apply LoRA to both q_proj and v_proj at minimum to enable adaptation of both attention weight computation and information aggregation",
      "Rank selection requires balancing adaptation capacity against overfitting risk, with ranks 4-16 suitable for most drone-specific domain shifts",
      "Library version pinning is essential in the PEFT ecosystem; misleading error messages from version mismatches are the most common source of debugging frustration",
      "Label masking for prompt tokens must be correctly set to -100 to prevent the model from learning to reproduce prompts instead of generating responses"
    ]
  },
  {
    page: 7,
    title: "Advanced Considerations: Scaling PEFT for Production Drone Systems",
    content: `As PEFT deployments scale from prototype to production across drone fleets, several advanced considerations become critical for maintaining system reliability and operational efficiency.

Adapter composition and stacking is an advanced technique where multiple LoRA adapters are applied simultaneously to the same base model. For drone applications, this enables combining a general flight-operations adapter with a mission-specific adapter. The general adapter might handle common visual processing tasks and standard drone command vocabulary, while the mission-specific adapter focuses on the particular inspection domain. Mathematically, the combined adaptation is the sum of the individual LoRA contributions: output equals W times x plus (B1 times A1) times x plus (B2 times A2) times x. This additive composition works well when the adapters address orthogonal aspects of the task but can cause interference when they try to adapt the same aspects in conflicting directions.

Continual learning with PEFT addresses the challenge of updating the model as new operational data accumulates without forgetting previously learned capabilities. Rather than retraining a single adapter from scratch each time, the approach maintains a growing dataset and periodically trains fresh adapters, or trains new adapters initialized from the weights of previous adapters. The key risk is catastrophic forgetting of earlier capabilities, which can be mitigated by including a representative sample of older training data in each training round (experience replay) or by constraining the LoRA weight updates to remain close to the previous adapter values (elastic weight consolidation).

The interaction between quantization precision and LoRA adaptation quality deserves careful attention at scale. While 4-bit NF4 quantization works well for many fine-tuning scenarios, certain model architectures or certain types of domain shifts may suffer noticeable quality degradation at 4-bit precision. Testing the same fine-tuning task at both 4-bit and 8-bit quantization and comparing the results on a validation set can reveal whether the additional memory savings of 4-bit are worth the potential quality trade-off for a specific application.

Adapter versioning and lifecycle management becomes essential when operating a fleet. Each adapter should be versioned with metadata including the base model identifier and version, the training dataset identifier and version, the LoRA configuration (rank, alpha, target modules), training metrics (loss, validation accuracy), and a unique version identifier. The ground control system must ensure that all drones in a fleet are running compatible base model and adapter versions, and must handle the rollout of new adapters gracefully, including rollback procedures if a new adapter performs poorly in the field.

Edge memory budgeting for multi-adapter deployment requires careful planning. On a Jetson Orin Nano with 8 GB of unified memory, the memory budget must accommodate the operating system (approximately 1 GB), the quantized base model (1-3 GB depending on model size), one or more loaded LoRA adapters (10-100 MB each), the inference runtime and buffers (1-2 GB), and camera input buffers and preprocessing (0.5-1 GB). This leaves limited headroom, and loading too many adapters simultaneously or failing to properly unload unused adapters can exhaust available memory. A well-designed adapter management system uses a least-recently-used caching strategy, keeping the most likely needed adapters in memory and loading others from fast storage on demand.

The training infrastructure for producing adapters at scale should be automated through a CI/CD pipeline. When new mission data is collected and validated, the pipeline automatically triggers adapter training, runs validation benchmarks against standard test sets, compares performance to the previous adapter version, and if the new version meets quality thresholds, promotes it to the deployment registry where it becomes available for fleet distribution. This automation removes the bottleneck of manual training management and enables continuous improvement at the pace of data collection.

Hardware-aware adapter design considers the specific capabilities of the target edge device. Some edge accelerators perform better with certain matrix dimensions due to their internal tiling and memory access patterns. Choosing a LoRA rank that aligns with the hardware tile size (often powers of 2 like 8, 16, or 32) can improve inference performance compared to arbitrary rank values that cause inefficient memory access patterns. Profiling the adapter inference on the actual target hardware, rather than assuming desktop performance characteristics transfer, is essential for meeting real-time latency requirements.`,
    key_takeaways: [
      "Adapter composition allows stacking multiple LoRA adapters for general plus mission-specific adaptation, but requires testing for interference between conflicting adaptations",
      "Production fleet management requires formal adapter versioning with base model compatibility tracking and automated rollout with rollback capability",
      "Edge memory budgeting must account for OS, base model, adapters, runtime, and input buffers, with least-recently-used caching for adapter management"
    ]
  },
  {
    page: 8,
    title: "Quiz Deep Dive Part 1: Questions 1 Through 10",
    content: `This section provides thorough explanations for the first ten quiz questions, examining why the correct answer is right and why each alternative is wrong.

Question 1: Main advantage of PEFT methods like LoRA? The correct answer is that it reduces the number of trainable parameters, enabling fine-tuning on consumer GPUs. LoRA typically trains less than 1% of the model parameters while achieving comparable results to full fine-tuning. The reduction in trainable parameters directly translates to reduced memory requirements for optimizer states and gradients, making consumer GPUs sufficient.

Question 2: What do r and alpha hyperparameters control in LoRA? The correct answer is the rank of the low-rank matrices and the scaling factor. The rank r determines the dimensionality of the decomposition matrices A and B, directly controlling the capacity of the adaptation. Alpha provides a scaling constant that modulates the magnitude of the LoRA update (applied as alpha/r). Other possible interpretations like learning rate and batch size are incorrect because these are standard training hyperparameters unrelated to the LoRA architecture. Model depth and width are structural parameters of the base model, not the adapter. Dropout and regularization are separate mechanisms from rank and scaling.

Question 3: Role of quantization in QLoRA? The correct answer is that it compresses the base model to 4-bit, reducing memory usage. Quantization specifically targets the frozen base model weights, converting them from 32-bit floating point to 4-bit NormalFloat representation since only the small LoRA parameters need full-precision gradients. Speed of inference alone is not the primary goal since QLoRA targets training-time memory reduction. Increasing model accuracy is incorrect since quantization inherently introduces some approximation error. Replacing LoRA adapters is wrong because quantization and LoRA are complementary techniques used together.

Question 4: Common target modules for LoRA in Transformers? The correct answer is the attention query and value projections (q_proj, v_proj). These layers are targeted because they control the core attention mechanism: q_proj determines what the model searches for, and v_proj determines what information is extracted from attended positions. The embedding layer is typically not targeted because it is shared across all positions and adapting it would change the representation of every token uniformly. The output classification head is usually retrained fully rather than adapted with LoRA. Normalization layers have very few parameters and applying LoRA to them would be architecturally inappropriate.

Question 5: What does get_peft_model do? The correct answer is that it freezes the base model and wraps it with LoRA layers. This function is the key transformation step: it takes an unmodified base model and a LoRA configuration, sets requires_grad to False for all existing parameters, and injects the trainable LoRA matrices at the specified target layers. It does not train the model (that is the Trainer's job). It does not save the model (that is an explicit save call). It does not load pretrained adapters (that would be PeftModel.from_pretrained).

Question 6: Why is QLoRA useful for drone AI development? The correct answer is that it allows fine-tuning of large vision-language models on the Jetson Orin Nano. The combination of 4-bit quantization and LoRA brings the memory requirements down to levels compatible with the limited unified memory available on Jetson platforms. It does not improve flight performance since QLoRA is a training technique, not a flight controller. It does not eliminate the need for training data since LoRA still requires domain-specific examples. It does not speed up inference speed since QLoRA primarily addresses training-time memory constraints.

Question 7: Memory reduction with 4-bit quantization vs 32-bit? The correct answer is 8x reduction. The arithmetic is straightforward: 32 bits divided by 4 bits equals 8. A model requiring 32 GB at full precision needs approximately 4 GB at 4-bit precision. 2x would correspond to 16-bit (half precision). 4x would correspond to 8-bit quantization. 16x would require 2-bit quantization, which is below the minimum practical precision for neural network weights.

Question 8: What does model.print_trainable_parameters() output? The correct answer is the number of trainable parameters versus total parameters. This function provides a diagnostic summary showing the exact count of parameters receiving gradients (the LoRA layers), the total parameter count (including frozen base model), and the percentage of trainable parameters. It does not show model architecture (that would be print(model)). It does not show training metrics (those come from the training loop). It does not show memory usage (that would require a profiling tool).

Question 9: Library used for 4-bit quantization? The correct answer is bitsandbytes. This library provides GPU-optimized implementations of various quantization schemes including NF4 and FP4, integrated with the Hugging Face ecosystem. PyTorch provides some quantization support but not the specific NF4 scheme used in QLoRA. TensorFlow is a different framework entirely. ONNX Runtime provides inference-time quantization but not the training-time quantization QLoRA requires.

Question 10: Purpose of lora_dropout? The correct answer is that it adds dropout to the LoRA layers to prevent overfitting. Dropout randomly zeros elements during training, preventing the small LoRA matrices from memorizing specific training examples. This is especially important for drone applications where training datasets are often small. It does not speed up training (dropout adds a small computational overhead). It does not reduce model size (dropout is only active during training). It does not improve quantization (dropout and quantization are independent mechanisms).`,
    key_takeaways: [
      "LoRA's r parameter controls adaptation capacity through matrix rank, while alpha scales the magnitude of the adaptation relative to frozen weights",
      "QLoRA's 4-bit quantization specifically targets frozen base model weights, not the LoRA adapter parameters which require full precision for gradient computation",
      "get_peft_model is the transformation function that converts a standard model into a LoRA-adapted model by freezing and injecting"
    ]
  },
  {
    page: 9,
    title: "Quiz Deep Dive Part 2: Questions 11 Through 20",
    content: `Question 11: What does target_modules in LoRAConfig specify? The correct answer is which layers of the base model to apply LoRA to. This list of module names (like q_proj, v_proj, k_proj) tells the PEFT library exactly where to inject the trainable low-rank matrices. The number of epochs is specified in training arguments. The learning rate schedule is configured in the optimizer settings. The output format is determined by the model architecture, not the LoRA configuration.

Question 12: Trainable parameters in LoRA vs full fine-tuning? The correct answer is about 0.1% to 1%. For a 7-billion parameter model with LoRA rank 8 applied to q_proj and v_proj across all layers, the trainable parameters typically number between 5 million and 30 million, which is 0.07% to 0.4% of the total. 10% to 20% would describe a partially frozen training approach, not LoRA. 50% would describe training half the model. 100% would be full fine-tuning.

Question 13: What does gradient_accumulation_steps do? The correct answer is that it accumulates gradients over multiple steps to simulate larger batch sizes. When GPU memory cannot support a large batch, gradient accumulation performs multiple forward-backward passes with small batches, summing the gradients before applying a single weight update. The effective batch size is per_device_batch_size times gradient_accumulation_steps. It does not skip training steps since every accumulation step performs a full forward-backward computation. It does not average gradients across GPUs since that is the role of distributed data parallelism. It does not reduce memory since each individual step still requires the same memory per sample.

Question 14: Purpose of data_collator? The correct answer is to format the dataset into batches and tokenize. The data collator takes individual examples from the dataset, groups them into batches, applies padding to ensure uniform sequence lengths within the batch, and prepares the tensor format expected by the model. It does not train the model (the Trainer handles the optimization loop). It does not evaluate the model (evaluation metrics are computed separately). It does not save checkpoints (the Trainer handles checkpointing based on the training arguments).

Question 15: Advantage of LoRA over full fine-tuning for drone commands? The correct answer is all of the above. LoRA provides multiple simultaneous advantages for drone command models: lower memory requirements (enabling training on accessible hardware), faster training time (fewer parameters means fewer gradient computations), the ability to store multiple lightweight adapters for different missions, and preservation of the base model's general capabilities through weight freezing. These advantages are complementary and all apply simultaneously.

Question 16: File containing trained LoRA adapter weights? The correct answer is adapter_model.bin. This file contains the serialized weights of only the LoRA matrices (the A and B matrices for each adapted layer). The adapter_config.json file accompanies it with the configuration metadata but does not contain weights. model.bin or pytorch_model.bin would contain the full base model weights. config.json contains the base model architecture configuration.

Question 17: What does device_map "auto" do? The correct answer is that it automatically distributes layers across available GPUs and CPU. The "auto" device map uses a heuristic to place as many layers as possible on the fastest available device (GPU) and spills remaining layers to slower devices (CPU memory, disk) when GPU memory is insufficient. It does not manually assign specific layers to specific devices (that would be a custom device map). It does not only use the CPU since it prioritizes GPU placement. It does not compress the model since device mapping is about placement, not compression.

Question 18: Role of bnb_4bit_quant_type? The correct answer is that it specifies the quantization algorithm (e.g., nf4, fp4). NormalFloat4 (nf4) places quantization levels according to the normal distribution of weights, while FP4 uses a standard 4-bit floating point representation. The choice between them affects the fidelity of the quantized representation. It does not set the number of bits since that is controlled by load_in_4bit. It does not configure the optimizer since quantization and optimization are independent. It does not control the model architecture since quantization is applied to the existing architecture without structural changes.

Question 19: Best description of parameter-efficient fine-tuning? The correct answer is that only a small subset of parameters are updated during training. This is the defining characteristic that distinguishes PEFT from full fine-tuning: the vast majority of model parameters remain frozen at their pre-trained values, and only the injected adapter parameters (or a small subset of existing parameters, depending on the method) receive gradient updates. All parameters being updated with a small learning rate would be full fine-tuning with a low learning rate, which is fundamentally different. Using fewer training examples describes data efficiency, not parameter efficiency. Reducing model size describes model compression or pruning, not PEFT.

Question 20: Typical output of a LoRA fine-tuned causal LM? The correct answer is a probability distribution over the next token. Causal language models, whether fine-tuned with LoRA or fully, generate text by predicting one token at a time. At each generation step, the model outputs logits over the entire vocabulary, which when passed through softmax become a probability distribution indicating the likelihood of each possible next token. A fixed text response would describe a retrieval system, not a generative model. A binary classification output would describe a discriminative classifier. An embedding vector would describe an encoder model used for similarity search.`,
    key_takeaways: [
      "Gradient accumulation enables effective large-batch training on memory-limited hardware by summing gradients across multiple small forward-backward passes",
      "The adapter_model.bin file contains only LoRA weights, typically under 100 MB, enabling efficient storage and transfer of multiple mission-specific adaptations",
      "Causal language models produce next-token probability distributions regardless of whether they were fine-tuned with LoRA or full fine-tuning"
    ]
  },
  {
    page: 10,
    title: "Summary and Self-Assessment",
    content: `This lesson has equipped you with both the theoretical understanding and practical knowledge needed to apply Parameter-Efficient Fine-Tuning techniques to drone AI systems. Let us consolidate the essential concepts and evaluate your readiness for the subsequent material.

The fundamental insight of PEFT is that fine-tuning large models does not require updating all parameters. The weight changes during fine-tuning occupy a low-rank subspace, meaning they can be efficiently approximated by small decomposition matrices. LoRA operationalizes this insight by injecting trainable pairs of low-rank matrices at strategic locations in the model (primarily the attention projections), while keeping the vast majority of the model frozen. The rank parameter controls the adaptation capacity, the alpha parameter scales the contribution, and dropout provides regularization against overfitting on small datasets.

QLoRA extends this efficiency by quantizing the frozen base model to 4-bit NormalFloat precision, achieving approximately 8x memory reduction. The NF4 scheme is specifically designed for neural network weights whose distribution approximates a Gaussian, placing quantization levels where they minimize information loss. The bitsandbytes library provides the GPU-optimized implementation of this quantization, integrated seamlessly with the Hugging Face training ecosystem.

The practical pipeline involves loading a quantized base model, applying LoRA configuration to inject adapter matrices, preparing domain-specific training data with proper tokenization and label masking, training with appropriate gradient accumulation for memory efficiency, and saving the resulting lightweight adapter for deployment. The adapter files are small enough to transmit over limited-bandwidth links, enabling remote reconfiguration of drone fleets.

For production deployment, the considerations extend to adapter versioning and lifecycle management, multi-adapter composition for layered specialization, continual learning strategies that prevent catastrophic forgetting, and edge memory budgeting that accounts for all system components sharing the unified memory pool.

The common pitfalls — from incorrect target module selection to version incompatibilities to label masking errors — represent practical knowledge that accelerates development when known in advance. Each pitfall has clear diagnostic indicators and straightforward solutions.

Self-Assessment Checkpoint: Before proceeding to the next lesson, verify your understanding of these core competencies.

Can you explain the mathematical decomposition that makes LoRA work, specifically why delta-W can be approximated as B times A where r is much smaller than the full matrix dimensions?

Given a model size and a target hardware memory budget, can you calculate whether QLoRA will fit, accounting for the base model at 4-bit, LoRA parameters at 16-bit, optimizer states, and runtime buffers?

Could you design a LoRA configuration for a new drone mission profile, selecting appropriate target modules, rank, alpha, and dropout values based on the complexity of the domain shift?

If a LoRA fine-tuning run produced high training accuracy but poor validation performance, could you diagnose whether the issue is rank selection, insufficient dropout, label masking errors, or dataset quality problems?

Can you articulate the operational workflow for deploying multiple LoRA adapters across a drone fleet, including versioning, distribution, loading, and rollback procedures?

Connection to the Track: This PEFT lesson connects directly to the preceding Vision Transformers lesson — LoRA is applied to the attention projections of the same transformer architecture you studied there. Going forward, the Production Optimization Stack lesson on quantization and distillation extends the deployment pipeline by showing how to further optimize the merged LoRA model for edge inference. The Sparsity and Pruning lesson introduces complementary model compression techniques that can be combined with LoRA for maximum efficiency. Understanding PEFT is the bridge between having powerful foundation models and being able to customize them for the specific, diverse requirements that drone operations demand.`,
    key_takeaways: [
      "PEFT through LoRA and QLoRA enables rapid, resource-efficient customization of foundation models for diverse drone mission profiles",
      "The complete pipeline from quantized model loading through LoRA training to lightweight adapter deployment transforms drone fleet AI management",
      "This lesson bridges the Vision Transformers architecture knowledge with practical deployment optimization covered in subsequent lessons on quantization, distillation, and pruning"
    ]
  }
];

writeFileSync("courses/drone_training.json", JSON.stringify(data, null, 2));
console.log("Done: Track 0 Lesson 1 (index 1) -", data.tracks[0].lessons[1].title);
console.log("Pages:", data.tracks[0].lessons[1].learning_script.length);
